
CREATE TABLE IF NOT EXISTS public.articoli (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome   VARCHAR(255) NOT NULL,
    prezzo NUMERIC(12,2) NOT NULL
);

INSERT INTO public.articoli (nome, prezzo) VALUES
('Penne', 1.50),
('Quaderno A4', 3.20),
('Cancelleria Pack', 9.90)
ON CONFLICT DO NOTHING;
